---
abstract: 'Extract the structure of a quoted mail message'
author:
  - 'Best Practical Solutions, LLC <modules@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Text::Quoted
name: Text-Quoted
no_index:
  directory:
    - inc
    - t
requires:
  Text::Autoformat: 0
  Text::Tabs: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: '2.09'
