name: Text-Quoted
module_name: Text::Quoted
version: 1.5
author: Jesse Vincent <jesse@bestpractical.com>
license: perl
distribution_type: module
requires:
  Text::Autoformat: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.33
